# Generated by Django 6.0.6 on 2026-06-13 19:39

import core.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fenomeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Fenômeno',
                'verbose_name_plural': 'Fenômenos',
            },
        ),
        migrations.CreateModel(
            name='GrupoTaxonomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Grupo Taxonômico',
                'verbose_name_plural': 'Grupos Taxonômicos',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=1000, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('formacao', models.CharField(max_length=1000, verbose_name='Graduação')),
            ],
            options={
                'verbose_name': 'Pesquisador',
                'verbose_name_plural': 'Pesquisadores',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('admin', models.BooleanField(default=False, verbose_name='Administrador?')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Temática',
                'verbose_name_plural': 'Temáticas',
            },
        ),
        migrations.CreateModel(
            name='TipoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Publicação',
                'verbose_name_plural': 'Tipos de Publicações',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comum', models.CharField(max_length=100, verbose_name='Nome Comum')),
                ('nome_cientifico', models.CharField(max_length=100, verbose_name='Nome Científico')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.buscar_ext, variations={'thumb': (300, 300)}, verbose_name='Foto')),
                ('fenomeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fenomeno', verbose_name='Fenômeno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupotaxonomico', verbose_name='Grupo Taxonômico')),
                ('local', models.ManyToManyField(to='core.local', verbose_name='Locais')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('ano', models.IntegerField(verbose_name='Ano de Publicação')),
                ('link', models.URLField(max_length=1000, verbose_name='Link')),
                ('autores', models.ManyToManyField(to='core.pesquisador', verbose_name='Autores')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupotaxonomico', verbose_name='Grupo Taxonômico')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tematica', verbose_name='Temática')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopublicacao', verbose_name='Tipo de Publicação')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
    ]
