# Generated by Django 6.0.6 on 2026-06-24 03:51

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.buscar_ext, variations={'thumb': (300, 300)}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
