# Generated by Django 6.0.6 on 2026-06-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pesquisador_foto_alter_local_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisador',
            name='formacao',
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='lattes',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='titulo',
            field=models.CharField(choices=[('Doutor', 'Doutor'), ('Mestre', 'Mestre'), ('Graduando', 'Graduando')], default='Graduando', max_length=10, verbose_name='Título'),
        ),
    ]
