# Generated by Django 6.0.6 on 2026-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pesquisador_formacao_pesquisador_lattes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='lattes',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Lattes'),
        ),
    ]
