# Generated by Django 6.0.6 on 2026-06-27 19:13

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pesquisador_lattes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.buscar_ext, variations={'thumb': (300, 300)}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='foto',
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='titulo',
            field=models.CharField(choices=[('Doutor', 'Doutor'), ('Mestre', 'Mestre'), ('Graduando', 'Graduando'), ('Pós-Doutor', 'Pós-Doutor'), ('Mestrando', 'Mestrando'), ('Doutorando', 'Doutorando')], default='Graduando', max_length=10, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ManyToManyField(blank=True, to='core.foto', verbose_name='Fotos'),
        ),
    ]
