# Generated by Django 6.0.6 on 2026-06-27 19:44

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_foto_remove_animal_foto_alter_pesquisador_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='foto',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.buscar_ext, variations={'thumb': (300, 300)}, verbose_name='Foto'),
        ),
    ]
