# Generated by Django 6.0.6 on 2026-06-27 19:54

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_animal_foto_delete_foto_animal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.buscar_ext, variations={'thumb': (300, 300)}, verbose_name='Foto'),
        ),
    ]
