# Generated by Django 6.0.6 on 2026-06-27 20:06

import core.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animal_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fenomeno',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='local',
        ),
        migrations.CreateModel(
            name='ImagemAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.buscar_ext, variations={'thumb': (300, 300)}, verbose_name='Foto')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal', verbose_name='Animal')),
                ('fenomeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fenomeno', verbose_name='Fenômeno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupotaxonomico', verbose_name='Grupo Taxonômico')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local', verbose_name='Locais')),
            ],
            options={
                'verbose_name': 'Imagem de Animal',
                'verbose_name_plural': 'Imagens de Animais',
            },
        ),
    ]
