# Generated by Django 6.0.6 on 2026-06-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_animal_fenomeno_remove_animal_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='endereco',
        ),
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
