# Generated by Django 6.0.6 on 2026-06-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_local_endereco_local_latitude_local_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('nivel', models.CharField(choices=[('Doutorado', 'Doutorado'), ('Mestrado', 'Mestrado'), ('Graduação', 'Graduação'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=100, verbose_name='Nível')),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Interrompida', 'Interrompida')], max_length=100, verbose_name='Status')),
                ('pesquisadores', models.ManyToManyField(to='core.pesquisador', verbose_name='Pesquisadores')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
            },
        ),
        migrations.AddField(
            model_name='publicacao',
            name='pesquisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pesquisa', verbose_name='Pesquisa'),
        ),
    ]
