# Generated by Django 6.0.6 on 2026-06-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pesquisa_publicacao_pesquisa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.RemoveField(
            model_name='imagemanimal',
            name='grupo',
        ),
        migrations.AddField(
            model_name='animal',
            name='grupo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.grupotaxonomico', verbose_name='Grupo Taxonômico'),
            preserve_default=False,
        ),
    ]
