# Generated by Django 6.0.6 on 2026-06-30 17:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_pessoa_remove_imagemanimal_grupo_animal_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemanimal',
            name='foto',
        ),
        migrations.AddField(
            model_name='imagemanimal',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to=core.models.buscar_ext, verbose_name='Mídia (Foto ou Vídeo)'),
        ),
    ]
