# Generated by Django 6.0.6 on 2026-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_imagemanimal_foto_imagemanimal_midia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='titulo',
            field=models.CharField(choices=[('Doutor', 'Doutor'), ('Doutora', 'Doutora'), ('Mestre', 'Mestre'), ('Graduando', 'Graduando'), ('Graduanda', 'Graduanda'), ('Pós-Doutor', 'Pós-Doutor'), ('Pós-Doutora', 'Pós-Doutora'), ('Mestrando', 'Mestrando'), ('Mestranda', 'Mestranda'), ('Doutorando', 'Doutorando'), ('Doutoranda', 'Doutoranda')], default='Graduando', max_length=20, verbose_name='Título'),
        ),
    ]
