# Generated by Django 6.0.6 on 2026-07-01 17:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pesquisador_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemanimal',
            name='midia',
            field=models.FileField(upload_to=core.models.buscar_ext, verbose_name='Mídia (Foto ou Vídeo)'),
        ),
    ]
