# Generated by Django 6.0.6 on 2026-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pesquisador_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=300, verbose_name='Título'),
        ),
    ]
