# Generated by Django 6.0.6 on 2026-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_publicacao_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemanimal',
            name='animal',
        ),
        migrations.AddField(
            model_name='imagemanimal',
            name='animais',
            field=models.ManyToManyField(to='core.animal', verbose_name='Animais'),
        ),
    ]
